### ISSUE TITLE
Installing “language-svg@0.3.0” failed.

### ISSUE THREAD

**Issue by uipoet** [erikdahlstrom/language-svg#1]
I see that your are up to 0.5.0 here in the repository. Here is the message I got attempting to install via latest ATOM:

```
Unable to download https://www.atom.io/api/packages/language-svg/versions/0.3.0/tarball: 400 Bad Request Repository inaccessible
```

**Comment by niccolomineo** [comment]
Same problem.

**Comment by brunowego** [comment]
+1

**Comment by yuvilio** [comment]
Same issue. I ended up just installing it manually:

``` bash
$ cd ~/.atom/packages/
$ git clone https://github.com/erikdahlstrom/language-svg
Cloning into 'language-svg'...
...
$ cd language-svg/
$ npm install
$
```

Restarted atom and SVG was available in the grammar selector.

**Comment by erikdahlstrom** [comment]
This was due to me moving the github repo, see https://github.com/atom/apm/issues/73#issuecomment-77463657. It should hopefully work fine from now on.
